// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6CljLf4GtSNujCKdzmxYk-j-hrgDYmU',
    appId: '1:1000974368302:web:4d47eb53b62a93b93769bf',
    messagingSenderId: '1000974368302',
    projectId: 'payzone-136b6',
    authDomain: 'payzone-136b6.firebaseapp.com',
    storageBucket: 'payzone-136b6.firebasestorage.app',
    measurementId: 'G-84CFX1614J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWmBR4oIc9CRZfIFoQ19L4mXllmS9VYxw',
    appId: '1:1000974368302:android:923ab88cf89d95ef3769bf',
    messagingSenderId: '1000974368302',
    projectId: 'payzone-136b6',
    storageBucket: 'payzone-136b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXMs46URrXI12TzTkMWdX6KJWh-LSu0Y',
    appId: '1:1000974368302:ios:8bff9119f0568d3b3769bf',
    messagingSenderId: '1000974368302',
    projectId: 'payzone-136b6',
    storageBucket: 'payzone-136b6.firebasestorage.app',
    iosBundleId: 'com.example.payzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbXMs46URrXI12TzTkMWdX6KJWh-LSu0Y',
    appId: '1:1000974368302:ios:8bff9119f0568d3b3769bf',
    messagingSenderId: '1000974368302',
    projectId: 'payzone-136b6',
    storageBucket: 'payzone-136b6.firebasestorage.app',
    iosBundleId: 'com.example.payzone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO6CljLf4GtSNujCKdzmxYk-j-hrgDYmU',
    appId: '1:1000974368302:web:4b907ead9aad509e3769bf',
    messagingSenderId: '1000974368302',
    projectId: 'payzone-136b6',
    authDomain: 'payzone-136b6.firebaseapp.com',
    storageBucket: 'payzone-136b6.firebasestorage.app',
    measurementId: 'G-TGVPYDZXDH',
  );
}
